export type CatalogEntry = {
  slug: string
  title: string
  category: string
  /** registry item this demo exercises; null for multi-component overviews */
  ui: string | null
  /** registry the ui item comes from; official items are vendored per style */
  source: "shadcn" | "@kibo-ui" | "@diceui" | "@magicui" | "@cult-ui" | "@animate-ui" | "@aceternity"
  /**
   * Set for full-page blocks (a whole dashboard/login page, not a small reusable component):
   * the real route that renders it live, so the gallery links out instead of trying to
   * squeeze a full page into a 224px preview card.
   */
  route?: string
}

export const catalog: CatalogEntry[] = [
  { slug: "demo", title: "Kitchen Sink", category: "Overview", ui: null, source: "shadcn" },
  { slug: "component-example", title: "Components Overview", category: "Overview", ui: null, source: "shadcn" },
  { slug: "button", title: "Button", category: "Forms & Inputs", ui: "button", source: "shadcn" },
  { slug: "button-group", title: "Button Group", category: "Forms & Inputs", ui: "button-group", source: "shadcn" },
  { slug: "checkbox", title: "Checkbox", category: "Forms & Inputs", ui: "checkbox", source: "shadcn" },
  { slug: "combobox", title: "Combobox", category: "Forms & Inputs", ui: "combobox", source: "shadcn" },
  { slug: "field", title: "Field", category: "Forms & Inputs", ui: "field", source: "shadcn" },
  { slug: "input", title: "Input", category: "Forms & Inputs", ui: "input", source: "shadcn" },
  { slug: "input-group", title: "Input Group", category: "Forms & Inputs", ui: "input-group", source: "shadcn" },
  { slug: "input-otp", title: "Input Otp", category: "Forms & Inputs", ui: "input-otp", source: "shadcn" },
  { slug: "label", title: "Label", category: "Forms & Inputs", ui: "label", source: "shadcn" },
  { slug: "native-select", title: "Native Select", category: "Forms & Inputs", ui: "native-select", source: "shadcn" },
  { slug: "radio-group", title: "Radio Group", category: "Forms & Inputs", ui: "radio-group", source: "shadcn" },
  { slug: "select", title: "Select", category: "Forms & Inputs", ui: "select", source: "shadcn" },
  { slug: "slider", title: "Slider", category: "Forms & Inputs", ui: "slider", source: "shadcn" },
  { slug: "switch", title: "Switch", category: "Forms & Inputs", ui: "switch", source: "shadcn" },
  { slug: "textarea", title: "Textarea", category: "Forms & Inputs", ui: "textarea", source: "shadcn" },
  { slug: "toggle", title: "Toggle", category: "Forms & Inputs", ui: "toggle", source: "shadcn" },
  { slug: "toggle-group", title: "Toggle Group", category: "Forms & Inputs", ui: "toggle-group", source: "shadcn" },
  { slug: "calendar", title: "Calendar", category: "Forms & Inputs", ui: "calendar", source: "shadcn" },
  { slug: "questionnaire", title: "Questionnaire", category: "Forms & Inputs", ui: "questionnaire", source: "shadcn" },
  { slug: "attachment", title: "Attachment", category: "Forms & Inputs", ui: "attachment", source: "shadcn" },
  { slug: "alert-dialog", title: "Alert Dialog", category: "Overlays", ui: "alert-dialog", source: "shadcn" },
  { slug: "context-menu", title: "Context Menu", category: "Overlays", ui: "context-menu", source: "shadcn" },
  { slug: "dialog", title: "Dialog", category: "Overlays", ui: "dialog", source: "shadcn" },
  { slug: "drawer", title: "Drawer", category: "Overlays", ui: "drawer", source: "shadcn" },
  { slug: "dropdown-menu", title: "Dropdown Menu", category: "Overlays", ui: "dropdown-menu", source: "shadcn" },
  { slug: "hover-card", title: "Hover Card", category: "Overlays", ui: "hover-card", source: "shadcn" },
  { slug: "menubar", title: "Menubar", category: "Overlays", ui: "menubar", source: "shadcn" },
  { slug: "popover", title: "Popover", category: "Overlays", ui: "popover", source: "shadcn" },
  { slug: "sheet", title: "Sheet", category: "Overlays", ui: "sheet", source: "shadcn" },
  { slug: "tooltip", title: "Tooltip", category: "Overlays", ui: "tooltip", source: "shadcn" },
  { slug: "command", title: "Command", category: "Overlays", ui: "command", source: "shadcn" },
  { slug: "sonner", title: "Sonner", category: "Overlays", ui: "sonner", source: "shadcn" },
  { slug: "breadcrumb", title: "Breadcrumb", category: "Navigation", ui: "breadcrumb", source: "shadcn" },
  { slug: "navigation-menu", title: "Navigation Menu", category: "Navigation", ui: "navigation-menu", source: "shadcn" },
  { slug: "pagination", title: "Pagination", category: "Navigation", ui: "pagination", source: "shadcn" },
  { slug: "tabs", title: "Tabs", category: "Navigation", ui: "tabs", source: "shadcn" },
  { slug: "sidebar", title: "Sidebar", category: "Navigation", ui: "sidebar", source: "shadcn" },
  { slug: "sidebar-icon", title: "Sidebar Icon", category: "Navigation", ui: "sidebar", source: "shadcn" },
  { slug: "sidebar-inset", title: "Sidebar Inset", category: "Navigation", ui: "sidebar", source: "shadcn" },
  { slug: "sidebar-floating", title: "Sidebar Floating", category: "Navigation", ui: "sidebar", source: "shadcn" },
  { slug: "accordion", title: "Accordion", category: "Data Display", ui: "accordion", source: "shadcn" },
  { slug: "avatar", title: "Avatar", category: "Data Display", ui: "avatar", source: "shadcn" },
  { slug: "badge", title: "Badge", category: "Data Display", ui: "badge", source: "shadcn" },
  { slug: "card", title: "Card", category: "Data Display", ui: "card", source: "shadcn" },
  { slug: "carousel", title: "Carousel", category: "Data Display", ui: "carousel", source: "shadcn" },
  { slug: "chart", title: "Chart", category: "Data Display", ui: "chart", source: "shadcn" },
  { slug: "collapsible", title: "Collapsible", category: "Data Display", ui: "collapsible", source: "shadcn" },
  { slug: "empty", title: "Empty", category: "Data Display", ui: "empty", source: "shadcn" },
  { slug: "item", title: "Item", category: "Data Display", ui: "item", source: "shadcn" },
  { slug: "kbd", title: "Kbd", category: "Data Display", ui: "kbd", source: "shadcn" },
  { slug: "table", title: "Table", category: "Data Display", ui: "table", source: "shadcn" },
  { slug: "marker", title: "Marker", category: "Data Display", ui: "marker", source: "shadcn" },
  { slug: "bubble", title: "Bubble", category: "Data Display", ui: "bubble", source: "shadcn" },
  { slug: "aspect-ratio", title: "Aspect Ratio", category: "Data Display", ui: "aspect-ratio", source: "shadcn" },
  { slug: "scroll-area", title: "Scroll Area", category: "Data Display", ui: "scroll-area", source: "shadcn" },
  { slug: "resizable", title: "Resizable", category: "Data Display", ui: "resizable", source: "shadcn" },
  { slug: "separator", title: "Separator", category: "Data Display", ui: "separator", source: "shadcn" },
  { slug: "alert", title: "Alert", category: "Feedback", ui: "alert", source: "shadcn" },
  { slug: "progress", title: "Progress", category: "Feedback", ui: "progress", source: "shadcn" },
  { slug: "skeleton", title: "Skeleton", category: "Feedback", ui: "skeleton", source: "shadcn" },
  { slug: "spinner", title: "Spinner", category: "Feedback", ui: "spinner", source: "shadcn" },
  // community registries — installed with the shadcn CLI, Radix-compatible, RTL-converted
  { slug: "tags-input", title: "Tags Input", category: "Forms & Inputs", ui: "tags-input", source: "@diceui" },
  { slug: "file-upload", title: "File Upload", category: "Forms & Inputs", ui: "file-upload", source: "@diceui" },
  { slug: "dropzone", title: "Dropzone", category: "Forms & Inputs", ui: "dropzone", source: "@kibo-ui" },
  { slug: "color-picker", title: "Color Picker", category: "Forms & Inputs", ui: "color-picker", source: "@kibo-ui" },
  { slug: "rating", title: "Rating", category: "Forms & Inputs", ui: "rating", source: "@kibo-ui" },
  { slug: "mini-calendar", title: "Mini Calendar", category: "Forms & Inputs", ui: "mini-calendar", source: "@kibo-ui" },
  { slug: "stepper", title: "Stepper", category: "Navigation", ui: "stepper", source: "@diceui" },
  { slug: "tree", title: "Tree View", category: "Data Display", ui: "tree", source: "@kibo-ui" },
  { slug: "kanban", title: "Kanban", category: "Data Display", ui: "kanban", source: "@kibo-ui" },
  { slug: "gantt", title: "Gantt", category: "Data Display", ui: "gantt", source: "@kibo-ui" },
  { slug: "timeline", title: "Timeline", category: "Data Display", ui: "timeline", source: "@diceui" },
  { slug: "sortable", title: "Sortable List", category: "Data Display", ui: "sortable", source: "@diceui" },
  { slug: "bento-grid", title: "Bento Grid", category: "Data Display", ui: "bento-grid", source: "@magicui" },
  { slug: "number-ticker", title: "Number Ticker", category: "Data Display", ui: "number-ticker", source: "@magicui" },
  { slug: "marquee", title: "Marquee", category: "Data Display", ui: "marquee", source: "@magicui" },
  { slug: "animated-beam", title: "Animated Beam", category: "Data Display", ui: "animated-beam", source: "@magicui" },
  { slug: "banner", title: "Banner", category: "Feedback", ui: "banner", source: "@kibo-ui" },
  { slug: "announcement", title: "Announcement", category: "Feedback", ui: "announcement", source: "@kibo-ui" },
  { slug: "dock", title: "Dock", category: "Navigation", ui: "dock", source: "@cult-ui" },
  { slug: "expandable", title: "Expandable Card", category: "Data Display", ui: "expandable", source: "@cult-ui" },
  { slug: "timer", title: "Timer", category: "Feedback", ui: "timer", source: "@cult-ui" },
  { slug: "typing-text", title: "Typing Text", category: "Data Display", ui: "primitives-texts-typing", source: "@animate-ui" },
  { slug: "highlight-text", title: "Highlight Text", category: "Data Display", ui: "primitives-texts-highlight", source: "@animate-ui" },
  { slug: "animated-tooltip", title: "Animated Tooltip", category: "Overlays", ui: "animated-tooltip", source: "@aceternity" },
  { slug: "flip-words", title: "Flip Words", category: "Data Display", ui: "flip-words", source: "@aceternity" },
  { slug: "wobble-card", title: "Wobble Card", category: "Data Display", ui: "wobble-card", source: "@aceternity" },
  { slug: "dashboard-01", title: "Dashboard", category: "Blocks", ui: "dashboard-01", source: "shadcn", route: "/dashboard" },
  { slug: "login-01", title: "Login", category: "Blocks", ui: "login-01", source: "shadcn", route: "/login-01" },
  { slug: "login-02", title: "Login (Cover Image)", category: "Blocks", ui: "login-02", source: "shadcn", route: "/login-02" },
  { slug: "login-03", title: "Login (Muted)", category: "Blocks", ui: "login-03", source: "shadcn", route: "/login-03" },
  { slug: "login-04", title: "Login (Form + Image)", category: "Blocks", ui: "login-04", source: "shadcn", route: "/login-04" },
  { slug: "login-05", title: "Login (Email Only)", category: "Blocks", ui: "login-05", source: "shadcn", route: "/login-05" },
  { slug: "signup-01", title: "Signup", category: "Blocks", ui: "signup-01", source: "shadcn", route: "/signup-01" },
  { slug: "signup-02", title: "Signup (Cover Image)", category: "Blocks", ui: "signup-02", source: "shadcn", route: "/signup-02" },
  { slug: "signup-03", title: "Signup (Muted)", category: "Blocks", ui: "signup-03", source: "shadcn", route: "/signup-03" },
  { slug: "signup-04", title: "Signup (Form + Image)", category: "Blocks", ui: "signup-04", source: "shadcn", route: "/signup-04" },
  { slug: "signup-05", title: "Signup (Social)", category: "Blocks", ui: "signup-05", source: "shadcn", route: "/signup-05" },
  { slug: "sidebar-01", title: "Sidebar (Grouped Nav)", category: "Blocks", ui: "sidebar-01", source: "shadcn", route: "/sidebar-01" },
  { slug: "sidebar-02", title: "Sidebar (Collapsible Sections)", category: "Blocks", ui: "sidebar-02", source: "shadcn", route: "/sidebar-02" },
  { slug: "sidebar-03", title: "Sidebar (Submenus)", category: "Blocks", ui: "sidebar-03", source: "shadcn", route: "/sidebar-03" },
  { slug: "sidebar-04", title: "Sidebar (Floating)", category: "Blocks", ui: "sidebar-04", source: "shadcn", route: "/sidebar-04" },
  { slug: "sidebar-05", title: "Sidebar (Collapsible Submenus)", category: "Blocks", ui: "sidebar-05", source: "shadcn", route: "/sidebar-05" },
  { slug: "sidebar-06", title: "Sidebar (Dropdown Submenus)", category: "Blocks", ui: "sidebar-06", source: "shadcn", route: "/sidebar-06" },
  { slug: "sidebar-07", title: "Sidebar (Icon Collapse)", category: "Blocks", ui: "sidebar-07", source: "shadcn", route: "/sidebar-07" },
  { slug: "sidebar-08", title: "Sidebar (Inset + Secondary Nav)", category: "Blocks", ui: "sidebar-08", source: "shadcn", route: "/sidebar-08" },
  { slug: "sidebar-09", title: "Sidebar (Nested Collapsible)", category: "Blocks", ui: "sidebar-09", source: "shadcn", route: "/sidebar-09" },
  { slug: "sidebar-10", title: "Sidebar (Popover)", category: "Blocks", ui: "sidebar-10", source: "shadcn", route: "/sidebar-10" },
  { slug: "sidebar-11", title: "Sidebar (File Tree)", category: "Blocks", ui: "sidebar-11", source: "shadcn", route: "/sidebar-11" },
  { slug: "sidebar-12", title: "Sidebar (Calendar)", category: "Blocks", ui: "sidebar-12", source: "shadcn", route: "/sidebar-12" },
  { slug: "sidebar-13", title: "Sidebar (Dialog)", category: "Blocks", ui: "sidebar-13", source: "shadcn", route: "/sidebar-13" },
  { slug: "sidebar-14", title: "Sidebar (Right)", category: "Blocks", ui: "sidebar-14", source: "shadcn", route: "/sidebar-14" },
  { slug: "sidebar-15", title: "Sidebar (Left + Right)", category: "Blocks", ui: "sidebar-15", source: "shadcn", route: "/sidebar-15" },
  { slug: "sidebar-16", title: "Sidebar (Sticky Header)", category: "Blocks", ui: "sidebar-16", source: "shadcn", route: "/sidebar-16" },
]

export const categories = [...new Set(catalog.map((e) => e.category))]

export function findEntry(slug: string) {
  return catalog.find((e) => e.slug === slug)
}
