import type { ComponentType } from "react"

export const exampleLoaders: Record<string, () => Promise<{ default: ComponentType }>> = {
  "demo": () => import("@/components/examples/demo").then((m) => ({ default: m.Demo })),
  "component-example": () => import("@/components/examples/component-example").then((m) => ({ default: m.ComponentExample })),
  "button": () => import("@/components/examples/button-example"),
  "button-group": () => import("@/components/examples/button-group-example"),
  "checkbox": () => import("@/components/examples/checkbox-example"),
  "combobox": () => import("@/components/examples/combobox-example"),
  "field": () => import("@/components/examples/field-example"),
  "input": () => import("@/components/examples/input-example"),
  "input-group": () => import("@/components/examples/input-group-example"),
  "input-otp": () => import("@/components/examples/input-otp-example"),
  "label": () => import("@/components/examples/label-example"),
  "native-select": () => import("@/components/examples/native-select-example"),
  "radio-group": () => import("@/components/examples/radio-group-example"),
  "select": () => import("@/components/examples/select-example"),
  "slider": () => import("@/components/examples/slider-example"),
  "switch": () => import("@/components/examples/switch-example"),
  "textarea": () => import("@/components/examples/textarea-example"),
  "toggle": () => import("@/components/examples/toggle-example"),
  "toggle-group": () => import("@/components/examples/toggle-group-example"),
  "calendar": () => import("@/components/examples/calendar-example"),
  "questionnaire": () => import("@/components/examples/questionnaire-example"),
  "attachment": () => import("@/components/examples/attachment-example"),
  "alert-dialog": () => import("@/components/examples/alert-dialog-example"),
  "context-menu": () => import("@/components/examples/context-menu-example"),
  "dialog": () => import("@/components/examples/dialog-example"),
  "drawer": () => import("@/components/examples/drawer-example"),
  "dropdown-menu": () => import("@/components/examples/dropdown-menu-example"),
  "hover-card": () => import("@/components/examples/hover-card-example"),
  "menubar": () => import("@/components/examples/menubar-example"),
  "popover": () => import("@/components/examples/popover-example"),
  "sheet": () => import("@/components/examples/sheet-example"),
  "tooltip": () => import("@/components/examples/tooltip-example"),
  "command": () => import("@/components/examples/command-example"),
  "sonner": () => import("@/components/examples/sonner-example"),
  "breadcrumb": () => import("@/components/examples/breadcrumb-example"),
  "navigation-menu": () => import("@/components/examples/navigation-menu-example"),
  "pagination": () => import("@/components/examples/pagination-example"),
  "tabs": () => import("@/components/examples/tabs-example"),
  "sidebar": () => import("@/components/examples/sidebar-example"),
  "sidebar-icon": () => import("@/components/examples/sidebar-icon-example"),
  "sidebar-inset": () => import("@/components/examples/sidebar-inset-example"),
  "sidebar-floating": () => import("@/components/examples/sidebar-floating-example"),
  "accordion": () => import("@/components/examples/accordion-example"),
  "avatar": () => import("@/components/examples/avatar-example"),
  "badge": () => import("@/components/examples/badge-example"),
  "card": () => import("@/components/examples/card-example"),
  "carousel": () => import("@/components/examples/carousel-example"),
  "chart": () => import("@/components/examples/chart-example"),
  "collapsible": () => import("@/components/examples/collapsible-example"),
  "empty": () => import("@/components/examples/empty-example"),
  "item": () => import("@/components/examples/item-example"),
  "kbd": () => import("@/components/examples/kbd-example"),
  "table": () => import("@/components/examples/table-example"),
  "marker": () => import("@/components/examples/marker-example"),
  "bubble": () => import("@/components/examples/bubble-example"),
  "aspect-ratio": () => import("@/components/examples/aspect-ratio-example"),
  "scroll-area": () => import("@/components/examples/scroll-area-example"),
  "resizable": () => import("@/components/examples/resizable-example"),
  "separator": () => import("@/components/examples/separator-example"),
  "alert": () => import("@/components/examples/alert-example"),
  "progress": () => import("@/components/examples/progress-example"),
  "skeleton": () => import("@/components/examples/skeleton-example"),
  "spinner": () => import("@/components/examples/spinner-example"),
}
